# Generated by Django 4.2.7 on 2026-02-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
    ]
