# Generated by Django 4.2.7 on 2026-02-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_beneficiary_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('MRU', 'Ouguiya Mauritanien'), ('DZD', 'Dinar Algérien'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='MRU', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='MRU', max_length=3),
        ),
    ]
