# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_otp_code_userprofile_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_reference_photo',
            field=models.ImageField(blank=True, help_text='Photo de référence (visage extrait au KYC) utilisée par /kyc/verify à chaque connexion par visage.', null=True, upload_to='face_reference/'),
        ),
    ]
