apiVersion: 1

policies:
  - orgId: 1
    receiver: contact-admin
    group_by: ['app', 'alertname']
    group_wait: 30s
    group_interval: 2m
    repeat_interval: 1h
    routes:
      - receiver: contact-trackpay
        matchers:
          - app =~ "trackpay.*"
        group_by: ['alertname']
        continue: true

      - receiver: contact-financeapp
        matchers:
          - app =~ "financeapp.*"
        group_by: ['alertname']
        continue: true

      - receiver: contact-nova
        matchers:
          - app =~ "nova.*"
        group_by: ['alertname']
        continue: true

      - receiver: contact-rssbank
        matchers:
          - app =~ "rss.*"
        group_by: ['alertname']
        continue: true
